name: sample_book_store
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.2
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.6
  collection: ^1.17.1
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.1
  build_runner: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/